export type Users = {
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  city: string;
};

export const users: Users[] = [
  {
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@example.com",
    phone: "415-234-5678",
    city: "San Francisco",
  },
  {
    firstName: "Michael",
    lastName: "Chen",
    email: "michael.chen@example.com",
    phone: "212-987-6543",
    city: "New York",
  },
  {
    firstName: "Emma",
    lastName: "Williams",
    email: "emma.williams@example.com",
    phone: "305-123-4567",
    city: "Miami",
  },
  {
    firstName: "David",
    lastName: "Rodriguez",
    email: "david.rodriguez@example.com",
    phone: "713-456-7890",
    city: "Houston",
  },
  {
    firstName: "Jessica",
    lastName: "Brown",
    email: "jessica.brown@example.com",
    phone: "602-789-0123",
    city: "Phoenix",
  },
  {
    firstName: "James",
    lastName: "Davis",
    email: "james.davis@example.com",
    phone: "215-345-6789",
    city: "Philadelphia",
  },
  {
    firstName: "Ashley",
    lastName: "Miller",
    email: "ashley.miller@example.com",
    phone: "210-678-9012",
    city: "San Antonio",
  },
  {
    firstName: "Christopher",
    lastName: "Wilson",
    email: "christopher.wilson@example.com",
    phone: "619-901-2345",
    city: "San Diego",
  },
  {
    firstName: "Amanda",
    lastName: "Moore",
    email: "amanda.moore@example.com",
    phone: "214-234-5678",
    city: "Dallas",
  },
  {
    firstName: "Matthew",
    lastName: "Taylor",
    email: "matthew.taylor@example.com",
    phone: "408-567-8901",
    city: "San Jose",
  },
  {
    firstName: "Lauren",
    lastName: "Anderson",
    email: "lauren.anderson@example.com",
    phone: "512-890-1234",
    city: "Austin",
  },
  {
    firstName: "Joshua",
    lastName: "Thomas",
    email: "joshua.thomas@example.com",
    phone: "904-123-4567",
    city: "Jacksonville",
  },
  {
    firstName: "Stephanie",
    lastName: "Jackson",
    email: "stephanie.jackson@example.com",
    phone: "414-456-7890",
    city: "Milwaukee",
  },
  {
    firstName: "Ryan",
    lastName: "White",
    email: "ryan.white@example.com",
    phone: "303-789-0123",
    city: "Denver",
  },
  {
    firstName: "Megan",
    lastName: "Harris",
    email: "megan.harris@example.com",
    phone: "206-012-3456",
    city: "Seattle",
  },
  {
    firstName: "Andrew",
    lastName: "Martin",
    email: "andrew.martin@example.com",
    phone: "617-345-6789",
    city: "Boston",
  },
  {
    firstName: "Nicole",
    lastName: "Garcia",
    email: "nicole.garcia@example.com",
    phone: "702-678-9012",
    city: "Las Vegas",
  },
  {
    firstName: "Brandon",
    lastName: "Clark",
    email: "brandon.clark@example.com",
    phone: "313-901-2345",
    city: "Detroit",
  },
  {
    firstName: "Rachel",
    lastName: "Lewis",
    email: "rachel.lewis@example.com",
    phone: "901-234-5678",
    city: "Memphis",
  },
  {
    firstName: "Kevin",
    lastName: "Lee",
    email: "kevin.lee@example.com",
    phone: "503-567-8901",
    city: "Portland",
  },
  {
    firstName: "Samantha",
    lastName: "Walker",
    email: "samantha.walker@example.com",
    phone: "615-890-1234",
    city: "Nashville",
  },
  {
    firstName: "Tyler",
    lastName: "Hall",
    email: "tyler.hall@example.com",
    phone: "405-123-4567",
    city: "Oklahoma City",
  },
  {
    firstName: "Brittany",
    lastName: "Allen",
    email: "brittany.allen@example.com",
    phone: "502-456-7890",
    city: "Louisville",
  },
  {
    firstName: "Jonathan",
    lastName: "Young",
    email: "jonathan.young@example.com",
    phone: "804-789-0123",
    city: "Richmond",
  },
  {
    firstName: "Danielle",
    lastName: "King",
    email: "danielle.king@example.com",
    phone: "816-012-3456",
    city: "Kansas City",
  },
  {
    firstName: "Nicholas",
    lastName: "Wright",
    email: "nicholas.wright@example.com",
    phone: "757-345-6789",
    city: "Virginia Beach",
  },
  {
    firstName: "Kayla",
    lastName: "Lopez",
    email: "kayla.lopez@example.com",
    phone: "402-678-9012",
    city: "Omaha",
  },
  {
    firstName: "Justin",
    lastName: "Hill",
    email: "justin.hill@example.com",
    phone: "918-901-2345",
    city: "Tulsa",
  },
  {
    firstName: "Heather",
    lastName: "Scott",
    email: "heather.scott@example.com",
    phone: "305-234-5678",
    city: "Tampa",
  },
  {
    firstName: "Aaron",
    lastName: "Green",
    email: "aaron.green@example.com",
    phone: "651-567-8901",
    city: "Minneapolis",
  },
  {
    firstName: "Melissa",
    lastName: "Adams",
    email: "melissa.adams@example.com",
    phone: "216-890-1234",
    city: "Cleveland",
  },
  {
    firstName: "Steven",
    lastName: "Baker",
    email: "steven.baker@example.com",
    phone: "412-123-4567",
    city: "Pittsburgh",
  },
  {
    firstName: "Christina",
    lastName: "Gonzalez",
    email: "christina.gonzalez@example.com",
    phone: "314-456-7890",
    city: "St. Louis",
  },
  {
    firstName: "Jason",
    lastName: "Nelson",
    email: "jason.nelson@example.com",
    phone: "513-789-0123",
    city: "Cincinnati",
  },
  {
    firstName: "Jennifer",
    lastName: "Carter",
    email: "jennifer.carter@example.com",
    phone: "407-012-3456",
    city: "Orlando",
  },
  {
    firstName: "Daniel",
    lastName: "Mitchell",
    email: "daniel.mitchell@example.com",
    phone: "702-345-6789",
    city: "Henderson",
  },
  {
    firstName: "Amy",
    lastName: "Perez",
    email: "amy.perez@example.com",
    phone: "919-678-9012",
    city: "Raleigh",
  },
  {
    firstName: "Eric",
    lastName: "Roberts",
    email: "eric.roberts@example.com",
    phone: "504-901-2345",
    city: "New Orleans",
  },
  {
    firstName: "Katherine",
    lastName: "Turner",
    email: "katherine.turner@example.com",
    phone: "716-234-5678",
    city: "Buffalo",
  },
  {
    firstName: "Mark",
    lastName: "Phillips",
    email: "mark.phillips@example.com",
    phone: "585-567-8901",
    city: "Rochester",
  },
  {
    firstName: "Sarah",
    lastName: "Campbell",
    email: "sarah.campbell@example.com",
    phone: "330-890-1234",
    city: "Akron",
  },
  {
    firstName: "Brian",
    lastName: "Parker",
    email: "brian.parker@example.com",
    phone: "419-123-4567",
    city: "Toledo",
  },
  {
    firstName: "Kelly",
    lastName: "Evans",
    email: "kelly.evans@example.com",
    phone: "937-456-7890",
    city: "Dayton",
  },
  {
    firstName: "Gregory",
    lastName: "Edwards",
    email: "gregory.edwards@example.com",
    phone: "859-789-0123",
    city: "Lexington",
  },
  {
    firstName: "Michelle",
    lastName: "Collins",
    email: "michelle.collins@example.com",
    phone: "270-012-3456",
    city: "Bowling Green",
  },
  {
    firstName: "Scott",
    lastName: "Stewart",
    email: "scott.stewart@example.com",
    phone: "423-345-6789",
    city: "Knoxville",
  },
  {
    firstName: "Lisa",
    lastName: "Sanchez",
    email: "lisa.sanchez@example.com",
    phone: "865-678-9012",
    city: "Chattanooga",
  },
  {
    firstName: "Robert",
    lastName: "Morris",
    email: "robert.morris@example.com",
    phone: "256-901-2345",
    city: "Huntsville",
  },
  {
    firstName: "Angela",
    lastName: "Rogers",
    email: "angela.rogers@example.com",
    phone: "205-234-5678",
    city: "Birmingham",
  },
  {
    firstName: "William",
    lastName: "Reed",
    email: "william.reed@example.com",
    phone: "334-567-8901",
    city: "Montgomery",
  },
  {
    firstName: "Aisha",
    lastName: "Khan",
    email: "aisha.khan@example.com",
    phone: "555-123-4567",
    city: "Manchester",
  },
  {
    firstName: "Ben",
    lastName: "Carter",
    email: "ben.carter@example.com",
    phone: "555-234-5678",
    city: "Birmingham",
  },
  {
    firstName: "Chloe",
    lastName: "Davis",
    email: "chloe.davis@example.com",
    phone: "555-345-6789",
    city: "Leeds",
  },
  {
    firstName: "Daniel",
    lastName: "Evans",
    email: "daniel.evans@example.com",
    phone: "555-456-7890",
    city: "Glasgow",
  },
  {
    firstName: "Emily",
    lastName: "Wilson",
    email: "emily.wilson@example.com",
    phone: "555-567-8901",
    city: "Liverpool",
  },
  {
    firstName: "Finn",
    lastName: "Thomas",
    email: "finn.thomas@example.com",
    phone: "555-678-9012",
    city: "Bristol",
  },
  {
    firstName: "Grace",
    lastName: "Roberts",
    email: "grace.roberts@example.com",
    phone: "555-789-0123",
    city: "Sheffield",
  },
  {
    firstName: "Harry",
    lastName: "Johnson",
    email: "harry.johnson@example.com",
    phone: "555-890-1234",
    city: "Edinburgh",
  },
  {
    firstName: "Isabelle",
    lastName: "Lewis",
    email: "isabelle.lewis@example.com",
    phone: "555-901-2345",
    city: "Cardiff",
  },
  {
    firstName: "Jack",
    lastName: "Walker",
    email: "jack.walker@example.com",
    phone: "555-012-3456",
    city: "Belfast",
  },
  {
    firstName: "Katie",
    lastName: "Green",
    email: "katie.green@example.com",
    phone: "521-112-2334",
    city: "Nottingham",
  },
  {
    firstName: "Liam",
    lastName: "Hall",
    email: "liam.hall@example.com",
    phone: "521-223-3445",
    city: "Southampton",
  },
  {
    firstName: "Mia",
    lastName: "Wood",
    email: "mia.wood@example.com",
    phone: "521-334-4556",
    city: "Newcastle",
  },
  {
    firstName: "Noah",
    lastName: "Jackson",
    email: "noah.jackson@example.com",
    phone: "521-445-5667",
    city: "Brighton",
  },
  {
    firstName: "Olivia",
    lastName: "White",
    email: "olivia.white@example.com",
    phone: "521-556-6778",
    city: "Leicester",
  },
  {
    firstName: "Peter",
    lastName: "Harris",
    email: "peter.harris@example.com",
    phone: "521-667-7889",
    city: "Coventry",
  },
  {
    firstName: "Quinn",
    lastName: "Martin",
    email: "quinn.martin@example.com",
    phone: "521-778-8990",
    city: "York",
  },
  {
    firstName: "Ruby",
    lastName: "Thompson",
    email: "ruby.thompson@example.com",
    phone: "521-889-9001",
    city: "Aberdeen",
  },
  {
    firstName: "Samuel",
    lastName: "Garcia",
    email: "samuel.garcia@example.com",
    phone: "521-990-0112",
    city: "Portsmouth",
  },
  {
    firstName: "Tara",
    lastName: "Martinez",
    email: "tara.martinez@example.com",
    phone: "522-001-1223",
    city: "Oxford",
  },
  {
    firstName: "Usman",
    lastName: "Robinson",
    email: "usman.robinson@example.com",
    phone: "522-112-2334",
    city: "Cambridge",
  },
  {
    firstName: "Violet",
    lastName: "Clark",
    email: "violet.clark@example.com",
    phone: "522-223-3445",
    city: "Exeter",
  },
  {
    firstName: "William",
    lastName: "Rodriguez",
    email: "william.rodriguez@example.com",
    phone: "522-334-4556",
    city: "Norwich",
  },
  {
    firstName: "Xara",
    lastName: "Lee",
    email: "xara.lee@example.com",
    phone: "522-556-6778",
    city: "Swansea",
  },
  {
    firstName: "Yusuf",
    lastName: "Scott",
    email: "yusuf.scott@example.com",
    phone: "522-667-7889",
    city: "Bath",
  },
  {
    firstName: "Zoe",
    lastName: "Adams",
    email: "zoe.adams@example.com",
    phone: "522-778-8990",
    city: "Plymouth",
  },
  {
    firstName: "Adam",
    lastName: "Baker",
    email: "adam.baker@example.com",
    phone: "531-121-2323",
    city: "Derby",
  },
  {
    firstName: "Bella",
    lastName: "Hill",
    email: "bella.hill@example.com",
    phone: "531-232-3434",
    city: "Stoke-on-Trent",
  },
  {
    firstName: "Charles",
    lastName: "King",
    email: "charles.king@example.com",
    phone: "531-343-4545",
    city: "Wolverhampton",
  },
  {
    firstName: "Diana",
    lastName: "Wright",
    email: "diana.wright@example.com",
    phone: "531-454-5656",
    city: "Reading",
  },
  {
    firstName: "Ethan",
    lastName: "Mitchell",
    email: "ethan.mitchell@example.com",
    phone: "531-565-6767",
    city: "Hull",
  },
  {
    firstName: "Fiona",
    lastName: "Campbell",
    email: "fiona.campbell@example.com",
    phone: "531-676-7878",
    city: "Preston",
  },
  {
    firstName: "George",
    lastName: "Anderson",
    email: "george.anderson@example.com",
    phone: "531-787-8989",
    city: "Milton Keynes",
  },
  {
    firstName: "Hannah",
    lastName: "Taylor",
    email: "hannah.taylor@example.com",
    phone: "531-898-9090",
    city: "Sunderland",
  },
  {
    firstName: "Isaac",
    lastName: "Moore",
    email: "isaac.moore@example.com",
    phone: "532-010-1212",
    city: "Luton",
  },
  {
    firstName: "Jessica",
    lastName: "Jones",
    email: "jessica.jones@example.com",
    phone: "532-121-2323",
    city: "Swindon",
  },
  {
    firstName: "Kevin",
    lastName: "Smith",
    email: "kevin.smith@example.com",
    phone: "532-232-3434",
    city: "Bournemouth",
  },
  {
    firstName: "Laura",
    lastName: "Brown",
    email: "laura.brown@example.com",
    phone: "532-343-4545",
    city: "Peterborough",
  },
  {
    firstName: "Michael",
    lastName: "Davis",
    email: "michael.davis@example.com",
    phone: "532-454-5656",
    city: "Warrington",
  },
  {
    firstName: "Nora",
    lastName: "Miller",
    email: "nora.miller@example.com",
    phone: "532-565-6767",
    city: "Slough",
  },
  {
    firstName: "Oscar",
    lastName: "Wilson",
    email: "oscar.wilson@example.com",
    phone: "532-676-7878",
    city: "Dundee",
  },
  {
    firstName: "Penelope",
    lastName: "Garcia",
    email: "penelope.garcia@example.com",
    phone: "532-787-8989",
    city: "Lancaster",
  },
  {
    firstName: "Ryan",
    lastName: "Williams",
    email: "ryan.williams@example.com",
    phone: "532-898-9090",
    city: "Salford",
  },
  {
    firstName: "Sophia",
    lastName: "Rodriguez",
    email: "sophia.rodriguez@example.com",
    phone: "543-010-1212",
    city: "Aberdeen",
  },
  {
    firstName: "Thomas",
    lastName: "Jones",
    email: "thomas.jones@example.com",
    phone: "543-121-2323",
    city: "Chelmsford",
  },
  {
    firstName: "Uma",
    lastName: "Taylor",
    email: "uma.taylor@example.com",
    phone: "543-232-3434",
    city: "Worcester",
  },
  {
    firstName: "Victor",
    lastName: "Brown",
    email: "victor.brown@example.com",
    phone: "543-343-4545",
    city: "Chester",
  },
  {
    firstName: "Wendy",
    lastName: "Davies",
    email: "wendy.davies@example.com",
    phone: "543-454-5656",
    city: "Canterbury",
  },
  {
    firstName: "Xavier",
    lastName: "Evans",
    email: "xavier.evans@example.com",
    phone: "543-565-6767",
    city: "Carlisle",
  },
  {
    firstName: "Zara",
    lastName: "Thomas",
    email: "zara.thomas@example.com",
    phone: "543-676-7878",
    city: "Durham",
  },
];
